language: node_js
node_js:
  - 8.11.3

jobs:
  include:
    - stage: build
      script: npm run lint:ci
      script: npm run build
    - stage: release
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
